name: Breaking Awesome
favicon: null
layout_spectrum: 0.26022
typography_spectrum: 0.253
title: + Breaking Awesome +
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#223b17'
    - '#879726'
    - '#fffeff'
    - '#5ebc79'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
