name: Breaking Awesome
favicon: null
layout_spectrum: 0.5018
typography_spectrum: 0.253
title: + Breaking Awesome +
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#007226'
    - '#afc9b3'
    - '#292679'
    - '#52578b'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
