name: Breaking Awesome
favicon: null
layout_spectrum: 0
typography_spectrum: 0.88394
title: Breaking Awesome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfcfa'
    - '#1698c3'
    - '#93a7e0'
    - '#87785d'
  brandStrength: 0.4893954
  lightness: 0.5220674
  saturation: 0.1627282
  rhythmicContrast: 0.5204082
purpose: []
