name: Breaking Awesome
favicon: null
layout_spectrum: 0.76128
typography_spectrum: 0.88394
title: Breaking Awesome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0f12'
    - '#ede9e6'
    - '#468bce'
    - '#bc4d3a'
    - '#b6b6b6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
