name: Breaking Awesome
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3388273
title: Aim for awesome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#223b17'
    - '#879726'
    - '#fffeff'
    - '#5ebc79'
  brandStrength: 0.4893954
  lightness: 0.5220674
  saturation: 0.1627282
  rhythmicContrast: 0.5204082
purpose: []
